services:
  ewm-stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats -d stats"]
      interval: 5s
      timeout: 5s
      retries: 10

  ewm-stats-service:
    build:
      context: .
      dockerfile: stats-service/stats-server/Dockerfile
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      ewm-stats-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9090/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 20
